export const CREATE_USER = "CREATE_USER";
export const CREATE_USER_FULFILLED = "CREATE_USER_FULFILLED";
export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_FULFILLED = "FETCH_USER_FULFILLED";
export const REQUEST_REJECTED = "REQUEST_REJECTED";
export const SET_USER_EMAIL = "SET_USER_EMAIL";
