/**
 * Action Types
 */

// USER ACTION TYPES
export const CREATE_USER = "CREATE_USER";
export const CREATE_USER_FULFILLED = "CREATE_USER_FULFILLED";
export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_FULFILLED = "FETCH_USER_FULFILLED";
export const SET_USER_EMAIL = "SET_USER_EMAIL";


// TASK ACTION TYPES
export const ADD_TASK = "ADD_TASK";
export const ADD_TASK_FULFILLED = "ADD_TASK_FULFILLED";
export const REMOVE_TASK = "REMOVE_TASK";
export const REMOVE_TASK_FULFILLED = "REMOVE_TASK_FULFILLED";
export const EDIT_TASK = "EDIT_TASK";
export const EDIT_TASK_FULFILLED = "EDIT_TASK_FULFILLED";


// ASYNC ACTION TYPES
export const REQUEST_REJECTED = "REQUEST_REJECTED";
